// Generated by gencpp from file yolo_ros_real_pose/ObjectsRealPose.msg
// DO NOT EDIT!


#ifndef YOLO_ROS_REAL_POSE_MESSAGE_OBJECTSREALPOSE_H
#define YOLO_ROS_REAL_POSE_MESSAGE_OBJECTSREALPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <yolo_ros_real_pose/RealPose.h>

namespace yolo_ros_real_pose
{
template <class ContainerAllocator>
struct ObjectsRealPose_
{
  typedef ObjectsRealPose_<ContainerAllocator> Type;

  ObjectsRealPose_()
    : header()
    , result()  {
    }
  ObjectsRealPose_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , result(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::yolo_ros_real_pose::RealPose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::yolo_ros_real_pose::RealPose_<ContainerAllocator> >::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::yolo_ros_real_pose::ObjectsRealPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolo_ros_real_pose::ObjectsRealPose_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectsRealPose_

typedef ::yolo_ros_real_pose::ObjectsRealPose_<std::allocator<void> > ObjectsRealPose;

typedef boost::shared_ptr< ::yolo_ros_real_pose::ObjectsRealPose > ObjectsRealPosePtr;
typedef boost::shared_ptr< ::yolo_ros_real_pose::ObjectsRealPose const> ObjectsRealPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolo_ros_real_pose::ObjectsRealPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolo_ros_real_pose::ObjectsRealPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolo_ros_real_pose::ObjectsRealPose_<ContainerAllocator1> & lhs, const ::yolo_ros_real_pose::ObjectsRealPose_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolo_ros_real_pose::ObjectsRealPose_<ContainerAllocator1> & lhs, const ::yolo_ros_real_pose::ObjectsRealPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolo_ros_real_pose

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::yolo_ros_real_pose::ObjectsRealPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo_ros_real_pose::ObjectsRealPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo_ros_real_pose::ObjectsRealPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo_ros_real_pose::ObjectsRealPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_ros_real_pose::ObjectsRealPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo_ros_real_pose::ObjectsRealPose_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolo_ros_real_pose::ObjectsRealPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1444762d660e4df67c4b755274867e92";
  }

  static const char* value(const ::yolo_ros_real_pose::ObjectsRealPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1444762d660e4df6ULL;
  static const uint64_t static_value2 = 0x7c4b755274867e92ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolo_ros_real_pose::ObjectsRealPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolo_ros_real_pose/ObjectsRealPose";
  }

  static const char* value(const ::yolo_ros_real_pose::ObjectsRealPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolo_ros_real_pose::ObjectsRealPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"RealPose[] result\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: yolo_ros_real_pose/RealPose\n"
"string label\n"
"float32 confidence\n"
"uint16 pix_lt_x\n"
"uint16 pix_lt_y\n"
"uint16 pix_rb_x\n"
"uint16 pix_rb_y\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 head_yaw\n"
"geometry_msgs/Pose local_pose\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::yolo_ros_real_pose::ObjectsRealPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolo_ros_real_pose::ObjectsRealPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectsRealPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolo_ros_real_pose::ObjectsRealPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolo_ros_real_pose::ObjectsRealPose_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "result[]" << std::endl;
    for (size_t i = 0; i < v.result.size(); ++i)
    {
      s << indent << "  result[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::yolo_ros_real_pose::RealPose_<ContainerAllocator> >::stream(s, indent + "    ", v.result[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_ROS_REAL_POSE_MESSAGE_OBJECTSREALPOSE_H
